baseURL = "https://ssnm.ctl.columbia.edu/"
googleAnalytics = "G-ZSJMBXBH8J"
metaDataFormat = "yaml"
languageCode = "en-us"
title = "Social Support Network Map"

[params]
    description = "The Social Support Network Map is an ecomap tool to help students and mental health professionals create digital social support maps. This tool helps you create an image that shows important people in the life of you or your client, tag those people as negative, neutral or positive supports, and assign them support attributes. It will help guide a discussion of if, where and how to engage supports for help."
    keywords = "ecomap, eco-map, social support network map, social support, social work"
    shortTitle = "SSNM"
